# kitty terminal configuration
# docs: https://sw.kovidgoyal.net/kitty/conf/

#: Cursor
cursor_shape block

#: Bell
# Visualize the bell instead of making noise
enable_audio_bell no
visual_bell_duration 0.2
visual_bell_color none

#: Background transparency (~90% see-through)
background_opacity 0.1
dynamic_background_opacity yes
